In [46]:
import numpy as np
from numpy import linalg as la

In [47]:
def add_elements(m,n):
    matrix=[]
    for x in range(m):
        row=[]
        print('Enter all the elements of row ',x,':')
        
        for y in range(n):
            temp=float(input())
            row.append(temp)
            
        matrix.append(row)
        
    return matrix

In [64]:
def Print(mat):
    print('\nMatrix: ')
    if type(mat[0])==list:
        for x in range(len(mat)):
            for y in range(len(mat[0])):
                print(mat[x][y],end='\t')
            print()

    else: 
        for x in range(len(mat)):
            print(mat[x],end='\t')
        print()

    return 

In [49]:
m=int(input('Enter no. of rows (m) of matrix (m×n):'))
n=int(input('Enter no. of cols (n) of matrix (m×n):'))
A=add_elements(m,n)

Enter all the elements of row  0 :
Enter all the elements of row  1 :


In [50]:
Print(A)

U = np.matmul(A, np.transpose(A))
U
# print('\nEigenvalues of given matrix are: ')
# print(la.eig(A)[0])

# print('\nEigenvectors of given matrix are: ')
# for x in la.eig(A)[1]:
#     print(x)


Matrix: 
3.0	2.0	2.0	
2.0	3.0	-2.0	


array([[17.,  8.],
       [ 8., 17.]])

In [51]:
V = np.matmul(np.transpose(A), A)
V

array([[13., 12.,  2.],
       [12., 13., -2.],
       [ 2., -2.,  8.]])

In [55]:
eig_vals = la.eig(U)
eig_vals

EigResult(eigenvalues=array([25.,  9.]), eigenvectors=array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]]))

In [65]:
lamb = []
ind=0
for x in range(m):
    arr=[]
    for y in range(n):
        if x==y:
            arr.append(np.round((np.sqrt(eig_vals[0][ind])),3))
            ind+=1
        else:
            arr.append(0)
    lamb.append(arr)

Print(lamb)


Matrix: 
5.0	0	0	
0	3.0	0	


In [68]:
U

array([[17.,  8.],
       [ 8., 17.]])

In [101]:
ueig= la.eig(U)[1]

for x in ueig:
    norm=0
    for y in x:
        norm+=y**2
    
    norm=norm**(1/2)

    for y in x:
        y=y/norm

ueig=np.transpose(ueig)
veig=np.round(ueig,8)
ueig

array([[ 0.70710678,  0.70710678],
       [-0.70710678,  0.70710678]])

In [102]:
veig= la.eig(V)[1]
print(veig)
for x in veig:
    norm=0
    for y in x:
        norm+=(y**2)
    
    norm=norm**(1/2)

    for y in x:
        y=y/norm

veig=np.transpose(veig)
veig=np.round(veig,8)
veig

[[-7.07106781e-01 -6.66666667e-01  2.35702260e-01]
 [-7.07106781e-01  6.66666667e-01 -2.35702260e-01]
 [-4.59701721e-17  3.33333333e-01  9.42809042e-01]]


array([[-0.70710678, -0.70710678, -0.        ],
       [-0.66666667,  0.66666667,  0.33333333],
       [ 0.23570226, -0.23570226,  0.94280904]])

In [100]:
b=np.matmul(lamb,veig)
z=np.matmul(ueig,b)
z

array([[-1.        , -3.77123619,  1.33333333],
       [-3.99999999, -0.94280905,  0.33333333]])